services:
  database:
    image: postgres:15-alpine
    container_name: emat-database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - emat-db-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: emat-backend:latest
    container_name: emat-backend
    env_file:
      - .env
    environment:
      DB_HOST: database
    depends_on:
      - database
    ports:
      - '8000:8000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: emat-frontend:latest
    container_name: emat-frontend
    env_file:
      - .env
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  emat-db-data: